# data augmentation
dataset:
  common:
    NAME: S3DIS_DatasetStage1
    voxel_size: 0.04
    overfit: -1
  train:
    split: train
    voxel_max: 7500
    loop: 5
    presample: False
  val:
    split: val
    voxel_max: null
    presample: True 
  test:
    split: test
    voxel_max: null
    presample: False

feature_keys: x
num_classes: 2
val_batch_size: 1

datatransforms:
  train: [ChromaticAutoContrast,PointsToTensor,RandomRotate,RandomFlip,RandomScale,PointCloudScaling,PointCloudJitter,ChromaticDropGPU]
  val: [PointsToTensor,RandomRotate]
  vote: [PointCloudScaling]
  kwargs:
    color_drop: 0.2
    jitter_sigma: 0.001
    jitter_clip: 0.005
    scale: [0.8, 1.2]
    angle: [1.0, 1.0, 1.0]
    normalize: False
batch_size: 64
dataloader:
  num_workers: 0

# ---------------------------------------------------------------------------- #
# Evaluation cfgs
# ---------------------------------------------------------------------------- #
num_votes: 10 
refine: True 

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #

# lr_scheduler:
lr: 0.001
min_lr: null
optimizer:
  NAME: adamw
  weight_decay: 1.0e-4  # the best 

criterion_args:
  NAME: Poly1FocalLoss

# scheduler
epochs: 300
sched: multistep
decay_epochs: [210, 270]
decay_rate: 0.1
warmup_epochs: 0


sched_on_epoch: True

grad_norm_clip: 1
use_voting: False

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
print_freq: 10
val_freq: 1

# ----------------- Model related
pretrained_path: null 

wandb:
  project: PointNext-ShapeNetPart